from django.conf.urls.defaults import *
from esmg.people.models import Person

urlpatterns = patterns('',
    (r'^$', 'esmg.people.views.list'),
    (r'^search/$', 'esmg.people.views.search'),
    (r'^csv/$', 'esmg.people.views.person_export'),
    (r'^(?P<slug>[\w-]+)/$', 'esmg.apparatus.views.page',
        dict(personpage=True)),
    (r'^(?P<slug>[\w-]+)/details/edit/$',
        'esmg.people.views.person_edit', dict(slug_field='slug')),
    (r'^(?P<slug>[\w-]+)/details/password/$',
        'esmg.people.views.password_edit', dict(slug_field='slug')),
    (r'^(?P<slug>[\w-]+)/resources/$', 'esmg.resources.views.list',
        dict(type="person_list")),
    (r'^(?P<slug>[\w-]+)/role/$', 'esmg.groups.views.role'),
    (r'^(?P<slug>[\w-]+)/resources/search/$', 'esmg.resources.views.search'),
    (r'^(?P<slug>[\w-]+)/resources/add/$', 'esmg.resources.views.create_resource',
        dict(source="person")),
    (r"^(?P<slug>[\w-]+)/resources/edit/(?P<object_id>\d+)/$", "esmg.resources.views.create_resource",
             dict(edit=True)),
    (r"^(?P<slug>[\w-]+)/resources/delete/(?P<object_id>\d+)/$", "esmg.resources.views.delete_resource"),
    (r'^(?P<slug>[\w-]+)/publications/$', 'esmg.publications.views.personpub'),
    (r'^(?P<slug>[\w-]+)/blog/$', 'esmg.comms.views.itemlist',
        dict(type="newsblog")),
    (r'^(?P<slug>[\w-]+)/blog/(?P<object_id>\d+)/$', 'esmg.comms.views.itemdetail',dict(type="newsblog")),
    (r'^(?P<slug>[\w-]+)/blog/post/$', 'esmg.comms.views.postitem',
        dict(type="newsblog")),
    (r'^(?P<slug>[\w-]+)/blog/edit/(?P<object_id>\d+)/$',
        'esmg.comms.views.edititem', dict(type="newsblog")),
    (r'^(?P<slug>[\w-]+)/blog/delete/(?P<object_id>\d+)/$',
        'esmg.comms.views.deleteitem', dict(type="newsblog")),

    # cms edit pages for the top level people pages
    (r'^(?P<uri>[\w-]+)/edit/$', 'esmg.apparatus.views.editpage',
        dict(create=False, personpage=True)),
    (r'^(?P<uri>[\w-]+)/versions/(?P<version>\d+)/$', 'esmg.apparatus.views.versions',
        dict(personpage=True)),
    (r'^(?P<uri>[\w-]+)/sidebaradd/$', 'esmg.apparatus.views.addsidebar',
        dict(personpage=True)),
    (r'^(?P<uri>[\w-]+)/sidebarremove/(?P<sidebar>[\d]+)/$',
        'esmg.apparatus.views.removesidebar', dict(personpage=True)),
    (r'^(?P<uri>[\w-]+)/create/$', 'esmg.apparatus.views.editpage',
        dict(create=True, personpage=True)),
    (r'^(?P<uri>[\w-]+)/move/$', 'esmg.apparatus.views.movepage',
            dict(personpage=True)),

    # cms pages below people pages
    (r'^(?P<uri>[\w\-/]+)/edit/$', 'esmg.apparatus.views.editpage',
        dict(create=False, personsubpage=True)),
    (r'^(?P<uri>[\w\-/]+)/create/$', 'esmg.apparatus.views.editpage',
        dict(create=True, personsubpage=True)),
    (r'^(?P<uri>[\w\-/]+)/delete/$', 'esmg.apparatus.views.deletepage',
        dict(personsubpage=True)),
    (r'^(?P<uri>[\w\-/]+)/versions/(?P<version>\d+)/$', 'esmg.apparatus.views.versions',
        dict(personsubpage=True)),
    (r'^(?P<uri>[\w\-/]+)/move/$', 'esmg.apparatus.views.movepage',
            dict(personsubpage=True)),
    (r'^(?P<uri>[\w\-/]+)/sidebaradd/$', 'esmg.apparatus.views.addsidebar',
        dict(personsubpage=True)),
    (r'^(?P<uri>[\w\-/]+)/sidebarremove/(?P<sidebar>[\d]+)/$', 'esmg.apparatus.views.removesidebar',
        dict(personsubpage=True)),
    (r'^(?P<uri>[\w\-/]+)/$', 'esmg.apparatus.views.page',
        dict(personsubpage=True)),
)
